config/routes.rb
Rails.application.routes.draw do

  resources :cart
  resources :itens_cart

  get 'limpar', :controller => 'itens_cart', :action => 'limpar'

  get 'current_cart', :controller => 'carts', :action => 'show', :id => 'current'

  resources :clientes

  devise_for :users, :controllers => { registrations: 'registrations' } 
  resources :posts do
    post "comments",to: "comments#create"
  end

  resources :produtos
  post 'payment_notifications', :controller => 'payment_notification', :action => 'create'

  delete "comments/:id",to: "comments#destroy", as: :comment

  root 'pages#welcome'

  get 'about' => 'pages#about'

  get 'como_funciona' => 'pages#como_funciona'

  get 'blog' => 'pages#blog'

  get 'servicos' => 'pages#servicos'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :itens_cart

  def preco_total
    # convert to array so it doesn't try to do sum on database directly
    itens_cart.to_a.sum(&:full_price)
  end

  def paypal_encrypted(return_url, notify_url)
    values = {
      :business => ENV["paypal_email"],
      :cmd => '_cart',
      :upload => 1,
      :return => return_url,
      :invoice => id,
      :notify_url => notify_url,
      :cert_id => ENV["paypal_cert_id"],
      :currency_code => 'CAD'
    }
    itens_cart.each_with_index do |item, index|
      values.merge!({
        "amount_#{index+1}" => item.preco,
        "item_name_#{index+1}" => item.produto.nome,
        "item_number_#{index+1}" => item.id,
        "quantity_#{index+1}" => 1
      })
    end
    encrypt_for_paypal(values)
  end
  
  PAYPAL_CERT_PEM = File.read("#{Rails.root}/certs/paypal_cert.pem")
  APP_CERT_PEM = File.read("#{Rails.root}/certs/app_cert.pem")
  APP_KEY_PEM = File.read("#{Rails.root}/certs/app_key.pem")

  def encrypt_for_paypal(values)
    signed = OpenSSL::PKCS7::sign(OpenSSL::X509::Certificate.new(APP_CERT_PEM), OpenSSL::PKey::RSA.new(APP_KEY_PEM, ''), values.map { |k, v| "#{k}=#{v}" }.join("\n"), [], OpenSSL::PKCS7::BINARY)
    OpenSSL::PKCS7::encrypt([OpenSSL::X509::Certificate.new(PAYPAL_CERT_PEM)], signed.to_der, OpenSSL::Cipher::Cipher::new("DES3"), OpenSSL::PKCS7::BINARY).to_s.gsub("\n", "")
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :authenticate_user!

  def show
    @cart = current_cart
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/carts/purchase.html.erb
<% title "Purchase Successful" %>

<p><strong>Thank you for your order!</strong> We will process it within one business day.</p>
<p><%= link_to "Back to Products", produtos_path %></p>

app/views/carts/show.html.erb
<h1>Comprar serviços<h1>

<table id="itens_cart" class="table table-bordered table-hover">
  <thead>
    <tr>
      <th><p>Produto</p></th>
      <th><p>Preco</p></th>
    </tr>
  </thead>
  <tbody>
    <% for itens_cart in @cart.itens_cart %>
      <tr>
        <td><%= itens_cart.produto.nome %></td>
        <td><%= format_price(itens_cart.produto.price) %></td>
      </tr>
    <% end %>
  </tbody>
  <tr>
    <td class="total" colspan="2">
      Total: <%= format_price(@cart.preco_total)%>
    </td>
  </tr>
</table>

<p>
  <%= link_to "Comprar mais serviços", servicos_url %>
  <!-- <%= link_to "Limpar", limpar_path %> --> 
</p>

<%if current_user.cliente != nil%>
  <%= form_tag ENV["paypal_url"] do %>
    <%= hidden_field_tag :cmd, "_s-xclick" %>
    <%= hidden_field_tag :encrypted, @cart.paypal_encrypted(servicos_url, payment_notifications_url(:secret => ENV["paypal_secret"])) %>
    <p><%= submit_tag "Finalizar compra", class: "btn btn-primary btn-lg" %></p>
  <% end %>
<%else%>
  <%= button_to "Continuar", new_cliente_path, :method => :get, class: "btn btn-primary btn-lg" %></td>
<%end%>