config/routes.rb
Rails.application.routes.draw do

  resources :cart
  resources :itens_cart

  get 'limpar', :controller => 'itens_cart', :action => 'limpar'

  get 'current_cart', :controller => 'carts', :action => 'show', :id => 'current'

  resources :clientes

  devise_for :users, :controllers => { registrations: 'registrations' } 
  resources :posts do
    post "comments",to: "comments#create"
  end

  resources :produtos
  post 'payment_notifications', :controller => 'payment_notification', :action => 'create'

  delete "comments/:id",to: "comments#destroy", as: :comment

  root 'pages#welcome'

  get 'about' => 'pages#about'

  get 'como_funciona' => 'pages#como_funciona'

  get 'blog' => 'pages#blog'

  get 'servicos' => 'pages#servicos'

end

app/models/produto.rb
class Produto < ActiveRecord::Base
  validates :nome, length: {minimum: 5, maximum: 40}, allow_blank: false
  validates :descricao, length: {minimum: 200, maximum: 7000}, allow_blank: false
  validates_presence_of [:price]

end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  load_and_authorize_resource
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto criado com Sucesso!' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto atualizado com sucesso!' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto excluido com sucesso!' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:nome, :descricao, :price, :image_url)
    end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= bootstrap_form_for(@produto) do |f| %>

  <%= f.text_field :nome, label: "Nome"%>

  <%= f.text_area :descricao, label: "Descrição" %>

  <%= f.number_field :price, label: "Preço", step: 2%>

  <%= f.submit "Salvar", class: "btn btn-primary btn-xs"%>

<% end %>

app/views/produtos/_produto.html.erb
<h2>
  <%= link_to produto.nome, produto %>
</h2>
<p><%= simple_format(produto.descricao) %></p>
<p><strong>Valor: <%=format_price(produto.price)%> (dólares canadenses)</strong></p>
<%if user_signed_in?%>
  <%= link_to "Contratar", itens_cart_index_path(:produto_id => produto), :method => :post, class: "btn btn-primary btn-lg enable glyphicon glyphicon-shopping-cart" %>
<%end%>

app/views/produtos/edit.html.erb
<h1>Editando Produto</h1>

<%= render 'form' %>

app/views/produtos/index.html.erb
<%if can? :update, @post%>
  <p id="notice"><%= notice %></p>

  <h1>Lista de produtos</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Descrição</th>
        <th>Preço</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @produtos.each do |produto| %>
        <tr>
          <td><%= produto.nome%></td>
          <td><%= truncate(produto.descricao, lenght: 100) %></td>  
          <td><%= produto.price %></td>
          <td><%= button_to "Mostrar", produto, :method => :get, class: "btn btn-primary btn-xs" %></td>
          <td><%= button_to "Editar", edit_produto_path(produto), :method => :get, class: "btn btn-warning btn-xs"%></td>
          <td><%= button_to "Excluir", produto, method: :delete, class: "btn btn-danger btn-xs", data: { confirm: 'Você tem certeza?' } %></td>            
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= button_to "Novo Produto", new_produto_path, :method => :get, class: "btn btn-primary btn-xs" %>
<%end%>

app/views/produtos/new.html.erb
<h1>Novo Produto</h1>

<%= render 'form' %>

app/views/produtos/show.html.erb
<%= render 'produtos/produto', produto: @produto%>