config/routes.rb
Rails.application.routes.draw do

  resources :cart
  resources :itens_cart

  get 'limpar', :controller => 'itens_cart', :action => 'limpar'

  get 'current_cart', :controller => 'carts', :action => 'show', :id => 'current'

  resources :clientes

  devise_for :users, :controllers => { registrations: 'registrations' } 
  resources :posts do
    post "comments",to: "comments#create"
  end

  resources :produtos
  post 'payment_notifications', :controller => 'payment_notification', :action => 'create'

  delete "comments/:id",to: "comments#destroy", as: :comment

  root 'pages#welcome'

  get 'about' => 'pages#about'

  get 'como_funciona' => 'pages#como_funciona'

  get 'blog' => 'pages#blog'

  get 'servicos' => 'pages#servicos'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new #Usuario ainda nao logado
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :itens_cart

  def preco_total
    # convert to array so it doesn't try to do sum on database directly
    itens_cart.to_a.sum(&:full_price)
  end

  def paypal_encrypted(return_url, notify_url)
    values = {
      :business => ENV["paypal_email"],
      :cmd => '_cart',
      :upload => 1,
      :return => return_url,
      :invoice => id,
      :notify_url => notify_url,
      :cert_id => ENV["paypal_cert_id"],
      :currency_code => 'CAD'
    }
    itens_cart.each_with_index do |item, index|
      values.merge!({
        "amount_#{index+1}" => item.preco,
        "item_name_#{index+1}" => item.produto.nome,
        "item_number_#{index+1}" => item.id,
        "quantity_#{index+1}" => 1
      })
    end
    encrypt_for_paypal(values)
  end
  
  PAYPAL_CERT_PEM = File.read("#{Rails.root}/certs/paypal_cert.pem")
  APP_CERT_PEM = File.read("#{Rails.root}/certs/app_cert.pem")
  APP_KEY_PEM = File.read("#{Rails.root}/certs/app_key.pem")

  def encrypt_for_paypal(values)
    signed = OpenSSL::PKCS7::sign(OpenSSL::X509::Certificate.new(APP_CERT_PEM), OpenSSL::PKey::RSA.new(APP_KEY_PEM, ''), values.map { |k, v| "#{k}=#{v}" }.join("\n"), [], OpenSSL::PKCS7::BINARY)
    OpenSSL::PKCS7::encrypt([OpenSSL::X509::Certificate.new(PAYPAL_CERT_PEM)], signed.to_der, OpenSSL::Cipher::Cipher::new("DES3"), OpenSSL::PKCS7::BINARY).to_s.gsub("\n", "")
  end
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  belongs_to :user

  validates :nome_completo, length: {minimum: 10, maximum: 250}, allow_blank: false
  validates :endereco_toronto, length: {minimum: 10, maximum: 300}, allow_blank: false
  validates :numero_voo, length: {minimum: 3, maximum: 100}, allow_blank: false
  validates :nome_escola, length: {minimum: 3, maximum: 300}, allow_blank: true
  validates :obs, length: {minimum: 0, maximum: 5000}, allow_blank: true   


  validates_presence_of [:user_id, :data_chegada, :data_hora_voo, :numero_voo, :tempo_permanencia]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :job   
  belongs_to :user

  validates :body, length: {minimum: 10, maximum: 500}, allow_blank: false
  validates_presence_of [:user_id, :post_id]

end

app/models/itens_cart.rb
class ItensCart < ActiveRecord::Base
  belongs_to :cart
  belongs_to :produto
  belongs_to :user

  validates :produto, uniqueness: { scope: :cart,message: "Produto ja incluido" }

  def full_price
    preco
  end
end

app/models/payment_notification.rb
class PaymentNotification < ActiveRecord::Base
  belongs_to :cart
  serialize :params
  after_create :mark_cart_as_purchased

  private


  def mark_cart_as_purchased
    if status == "Completed" && params[:secret] == ENV["paypal_secret"] &&
        params[:receiver_email] == ENV["paypal_email"] &&
        params[:mc_gross] == cart.preco_total.to_s && params[:mc_currency] == "CAD"

      cart = Cart.find(cart_id)
      cart.update_attribute(:purchased_at, Time.now)
      cart.itens_cart[0].user.cliente.update_attribute(:ativo, true)

      PaymentMailer.payment_confirmation(cart.itens_cart[0].user).deliver
      
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  mount_uploader :image, ImageUploader
  validates :title, length: {minimum: 5, maximum: 40}, allow_blank: false
  validates :content, length: {minimum: 100, maximum: 10000}, allow_blank: false

  validates_presence_of [:image]
end

app/models/produto.rb
class Produto < ActiveRecord::Base
  validates :nome, length: {minimum: 5, maximum: 40}, allow_blank: false
  validates :descricao, length: {minimum: 200, maximum: 7000}, allow_blank: false
  validates_presence_of [:price]

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments   
  has_many :itens_cart 
  has_one :cliente
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  def admin?
    admin
  end

  validates :email, length: {minimum: 5, maximum: 250}, allow_blank: false
  validates :username, length: {minimum: 5, maximum: 70}, allow_blank: false
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :authenticate_user!

  def show
    @cart = current_cart
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
end
  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
    nil
  end

  def format_price(number)
    number_to_currency number,
      unit: "$",
      separator: ",",
      delimiter: "."
  end

end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/cliente_helper.rb
module ClienteHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/itens_cart_helper.rb
module ItensCartHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrueToronto</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="google-site-verification" content="zYcGltl4BqUQcXkJmxOsVMs2uP35lvrmTJ0CxhIxcx4" />
  </head>
  <body>
    
    <div class="navbar navbar-default navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <%if user_signed_in?%>
              <li><%= link_to "Olá " + current_user.username + "!",root_url %></li>
            <%end%>
            <li><%= link_to "Home", root_url %></li>
            <li><%= link_to "Blog", blog_url %></li>
            <li><%= link_to "Serviços", servicos_url %></li>
            <li><%= link_to "Quem somos", about_url %></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
              <%if user_signed_in?%>
              <%if can? :update, @post%>
                <li><%= link_to "Editar posts", posts_url %></li>
                <li><%= link_to "Editar produtos", produtos_url%></li>
              <%end%>
              <li><%= link_to 'Sua conta', edit_user_registration_path %></li>
              <%if (current_user.cliente != nil) && (current_user.cliente.ativo) %>
                <li><%= link_to 'Dados sua viagem', edit_cliente_path(current_user.cliente), method: :get %></li>
              <%end%>
              <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "navbar-right"%></li>
            <%else%>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Login", new_user_session_path %></li>
            <%end%>
          </ul>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="jumbotron" style="background-image: url('/assets/capa.jpg'); background-size: cover%; color: white !important;">
        <h1>True Toronto</h1>
        <p>O serviço que vai te fazer economizar tempo e dinheiro no Canada!</p>
        <%= button_to "Conheça!", como_funciona_path, :method => :get, class: "btn btn-primary btn-lg" %></td>
      </div>
    </div>

    <div class="container">      
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <%= flash_messages %>
          <%= yield %>
        </div>
      </div>
    </div> 
  </body>
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-4">&copy; 2015 True Toronto</div>
      </div>
    </div>
  </footer>    
</html>

app/views/pages/about.html.erb
<div id="quem_somos">
<h1>Quem Somos</h1>

  <div class="row">
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <img src="https://scontent-yyz1-1.xx.fbcdn.net/hprofile-xfa1/v/t1.0-1/c62.0.160.160/p160x160/1497799_559938170784673_7013112987791469360_n.jpg?oh=6d7f8735b72f42467c8b323d24e4c5f5&oe=56B6EC78">
        <div class="caption">
          <h3>Filipe</h3>
          <p>Analista de sistemas por formação Paulista do interior morador de Toronto.</p>
        </div>
      </div>
    </div>

    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <img src="https://scontent-yyz1-1.xx.fbcdn.net/hprofile-xft1/v/t1.0-1/p160x160/11990582_1068205499864398_203311983094196147_n.jpg?oh=8b70c64e5112b3fc78ddda2514b5d237&oe=56B7B4AF">
        <div class="caption">
          <h3>Eduardo</h3>
          <p>Administrador por formação. Nascido em Florianopolis e atualmente estudando e trabalhando em Toronto.</p>
        </div>
      </div>
    </div>

    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <img src="https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xap1/v/t1.0-1/p160x160/1454584_640370349348055_2055557065_n.jpg?oh=c9d71b1fd70fb6bcbfee3f34372fa986&oe=56AF9A96&__gda__=1458430004_f0932b2eb4af5a90ead5493b4a6274e5">
        <div class="caption">
          <h3>Renato</h3>
          <p>Goianiense, Engenheiro Civil e atualmente morando em Toronto.</p>
        </div>
      </div>
    </div>  
    
  </div>
</div>

app/views/pages/blog.html.erb
<% @posts.each do |post| %>
  <%= render 'posts/post', post: post%>
<%end%>
<%= will_paginate @posts, renderer: BootstrapPagination::Rails, :previous_label => 'anterior', :next_label => 'proxima'%>

app/views/pages/como_funciona.html.erb
<div id="como_funciona">
  <h2>Como funciona o TrueToronto?</h2>

  <h3>Nossos serviços consistem em várias etapas!</h3>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Parte 1 (pós a contratação)</h3>
    </div>
    <div class="panel-body">
      <ul>
        <li>Você preencheu os dados de sua viagem em nosso site no processo de contratação do nosso serviço, e recebeu o Email de confirmação.</li>
        <li>As Informações de sua viajem ficaram disponíveis em nosso site "Dados sua viagem".</li>
        <li>Nesta etapa existe um campo livre onde você pode descrever algo que deseja conhecer ou alguma dificuldade especifica que esteja enfrentando, fique à vontade para nos dizer assim conseguimos endereçar melhor suas dificuldades.</li>
      </ul>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Parte 2 (Planejamento)</h3>
    </div>
    <div class="panel-body">
      <strong>Após 3 dias úteis da contratação do serviço vamos mandar em seu email um planejamento inicial com base em suas informações. Essas informações incluem:</strong>
        <ul>
          <li>Lista de locais próximos a sua estadia (Mercados, lojas, shoppings e etc).</li>
          <li>Rota detalhada de como chegar à escola usando transporte público, bem como os valores e como utilizar o transporte em Toronto.</li>
          <li>Um guia que montamos mostrando os melhores lugares para comprar o básico (comida, produtos de limpeza, material escolar e etc) na cidade.</li>
          <li>Guia de telefonia (operadoras, planos e preços).</li>
          <li>Bancos, onde e como abrir uma conta no Canada.</li>
          <li>Pontos turísticos mais badalados.</li>
          <li>Baladas, bares e restaurantes vida noturna de Toronto.</li>
        </ul>         
    </div>
  </div>  

  <h3>Serviços específicos de cada pacote (as etapas 1 e 2 são comuns a todos os serviços)</h3>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Pacote Budget</h3>
    </div>
    <div class="panel-body">
      <p>Neste pacote te encontraremos pessoalmente em Toronto em 1 oportunidade, com duração de 3 horas no final de semana onde vamos te mostrar a vida na cidade na prática.</p>
      <p>Neste dia temos como sugestão mostrar as dicas do transporte público e mostrar o caminho para sua escola (lembrando o serviço é pessoal portanto essa seria uma sugestão caso queira conhecer outro ponto basta avisar nossa equipe).</p>
      <p>Caso seja o caso te mostramos onde fazer seu id de estudante, quais dias comprar os passes do transporte público, quais são e onde estão os bancos.</p>
      <p>O encontro termina no Eaton centre (shopping famoso de Toronto), onde vamos te mostrar as lojas das operadoras de telefonia, principais lojas e a entrada para o Subterrâneo (muito util durante o inverno).</p>
    </div>
  </div>  

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Pacote Vip</h3>
    </div>
    <div class="panel-body">
      <p>Neste pacote te encontraremos em 3 oportunidades na cidade, todas elas com duração de 3 horas sendo que um dos encontros acontece em uma sexta feira com o intuito de mostrar a cidade em um dia normal da semana.</p>
      <p>Neste pacote a nossa sugestão seria dividir as tarefas, no primeiro encontro vamos te dar as dicas do transporte público, te levar na escola te mostrando os melhores caminhos basicamente a mesma sugestão do pacote Budget.</p>
      <p>No segundo encontro seria a sexta feira para mostrar quais dificuldades você vai enfrentar em um dia normal da semana (Rush hour), e quais as dicas para fugir de algumas delas. No final deste encontro vamos te mostrar os principais locais que ficam proximos ao seu endereço.</p>
      <p>No terceiro encontro te levamos nos principais pontos turísticos da cidade e damos dicas de como economizar um bom dinheiro para visitar cada um deles.</p>
      <p>Neste pacote te auxiliamos também na contratação de um plano de telefonia caso deseje.</p>
    </div>
  </div>    

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">True Toronto</h3>
    </div>
    <div class="panel-body">
      <p>Este é o nosso pacote completo, ele possui todos os 3 encontros do pacote Vip e além disso você tem um canal aberto com nossa equipe onde pode tirar suas dúvidas sobre a cidade durante 2 semanas(lembrando que este canal respeita as regras do nossos termos de uso).</p>

      <p>Outro ponto adiconal neste pacote te levamos pessoalmente aos melhores supermercados e lojas da cidade e te mostramos na prática dicas de como economizar com comida, roupas e produtos basicos sugerindo um planejamento de acordo com suas necessidades e claro seu orçamento.</p>
    </div>
  </div>

  <h3>Confira nossa página de <a href="/servicos">serviços</a> e veja qual melhor se adapta a suas necessidades!</h3>

  <h3>Ainda tem dúvidas fale com nossa equipe truetoronto@truetoronto.com.br</h3>

</div>

app/views/pages/servicos.html.erb
<% @produtos.each do |produto| %>
  <%= render 'produtos/produto', produto: produto%>
<%end%>

app/views/pages/welcome.html.erb
<div id="welcome">

<div class="panel panel-default">
  <div class="panel-body">
    <h2>Olá, nós somos um trio de Brasileiros que atualmente reside em Toronto e vai ajudar você a tornar sua viagem muito mais proveitosa!</h2>

    <h3>Agora você deve estar pensando "mas como?"</h3>

    <h4>Passamos pelas mais diversas dificuldades e sabemos exatamente quais problemas um estrangeiro vai encontrar na cidade.</h4>
    <h4>Nossos serviços vão fazer você economizar muito tempo e dinheiro!</h4>
    <h4>Assim você se concentra em executar seus planos e não perde o sono com alguns problemas que enfrentamos!</h4>

    <h4>Citando alguns pontos:</h4>
  </div>
</div>

  <div class="row">
    <div class="col-sm-12 col-md-12">
      <div class="thumbnail">
        <a title="By Secondarywaltz (Own work) [CC BY-SA 3.0 (http://creativecommons.org/licenses/by-sa/3.0)], via Wikimedia Commons" href="https://commons.wikimedia.org/wiki/File%3ASt_George_TTC_Rocket.jpg"><img width="512" alt="St George TTC Rocket" src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/St_George_TTC_Rocket.jpg/512px-St_George_TTC_Rocket.jpg"/></a>
          <p>Muita gente pensa: "OK! O país é de primeiro mundo, o transporte público também é de primeiro mundo." não é bem assim!</p>
          <p>Existem alguns detalhes que podem fazer você economizar um bom tempo, e o melhor, um bom dinheiro se você souber usar corretamente o transporte público de Toronto (descontos para estudantes, passes mensais e etc).</p>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12 col-md-12">
      <div class="thumbnail">
        <img src="/assets/rent_tratada.jpg" class="img-responsive" alt="Responsive image" style=" max-width: 100% !important; height: auto; display: inline-block;">
        <div class="caption">
          <h3>Homestay, aluguel e outras moradias</h3>
          <p>Ajudamos a valiar qual a melhor opção de moradia para sua viagem, mostrando vantagens e desvantagens de cada uma delas de um modo que só quem vive em Toronto sabe descrever!</p>
          <p>Toronto possui uma dificuldade que a maioria dos lugares nos quais pesquisei antes da minha viagem não cita, a maioria dos anúncios de imóveis para aluguel exigem uma comprovação de renda, exigência que me fez perder muito tempo procurando e visitando lugares.</p>
          <p>Nós te ajudamos a procurar por moradias especificas para estudantes ou residentes temporários, e até mesmo visitamos os lugares caso você ainda esteja no Brasil e claro te damos dicas sobre valores e localizações.</p>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12 col-md-12">
      <div class="thumbnail">
        <img src="/assets/Mercado_truetoronto.jpg" class="img-responsive" alt="Responsive image" style=" max-width: 100% !important; height: auto; display: inline-block;">
        <div class="caption">
          <h3>Alimentação e vestuário</h3>
          <p>Parece ser um tópico simples porém e possível economizar muito dinheiro comprando esses itens nos lugares corretos. Como alimentação e algo diário qualquer economia é bem-vinda, nós auxiliamos nestes pontos com base em onde você vai morar aqui na cidade, daremos dicas de mercados, restaurantes, lojas, brechós e etc.</p>
          <p>Um ponto que também vamos levar em consideração e que você esta vindo do Brasil um pais tropical e não tem roupas para o inverno de Toronto, somente neste ponto e possível fazer uma economia gigantesca sabendo quais itens comprar, como e onde procurar.</p>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12 col-md-12">
      <div class="thumbnail">
        <img src="/assets/turismo_image.jpg" class="img-responsive" alt="Responsive image" style=" max-width: 100% !important; height: auto; display: inline-block;">
        <div class="caption">
          <h3>Passeios e turismo</h3>
          <p>Toronto e uma cidade com várias atrações turísticas, porém existem uma serie e dicas que podem fazer você ter acesso a essas atrações pagando muito menos e aproveitando muito mais. Outro ponto que auxiliamos de maneira exclusiva, você pode nos dizer os pontos que gostarias de conhecer e nós traçamos um plano com as dicas, ou caso ainda não saiba nós mostramos as opções mais visitadas da cidade e você escolhe quais visitar.</p>
          <p>Damos dicas de Museus, Zoológico, passeios ao ar livre até a vida noturna de Toronto a cidade possui os mais diversos tipos de atrações. Tudo de acordo com suas escolhas.</p>
        </div>
      </div>
    </div>
  </div>
  
  <h4>Esses itens que citei são alguns pontos que podemos te ajudar, visite nossa pagina de <a href="/servicos"> serviços </a> e <a href="/como_funciona">entenda </a> como funcionam. Tenho certeza que você vai gostar! te oferecemos serviços exclusivos com base em seus planos de viagem!</h4>
  <h4>Acompanhe nosso <a href="/blog">Blog</a>, temos novos posts todas as sextas-feiras!</h4>

</div>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>